### ISSUE TITLE
Can't link external dependecies

### ISSUE THREAD

**Issue by Hilbertdotx** [Elias-Gu/MPM2D#1]
When I trying to compile the code, I put it into vs 2015 and add the include and libraries directories in Project Properties, and it shows the link error as:
![Capture](https://user-images.githubusercontent.com/23475333/74184072-b9932180-4c0b-11ea-90bd-89100bff090e.PNG)

Could you tell us how you configure your vs?

Thank you in advance.

**Comment by Hilbertdotx** [comment]
I have solved this problem. GLFW need support from opengl. Just need to add "opengl32.lib" in Project->Properties->Linker->Input->Additional Dependency.

**Comment by Elias-Gu** [comment]
Glad it worked!
