### ISSUE TITLE
无法解析的外部符号

### ISSUE THREAD

**Issue by YunkangTao** [Elias-Gu/MPM2D#2]

**Comment by Elias-Gu** [comment]
Is it possible that these files have not been included in the project directory? Same thing has to be done with the libraries.
https://stackoverflow.com/questions/2676417/how-do-include-paths-work-in-visual-studio

**Comment by YunkangTao** [comment]
> Is it possible that these files have not been included in the project directory? Same thing has to be done with the libraries.
> https://stackoverflow.com/questions/2676417/how-do-include-paths-work-in-visual-studio

Thank you so much. I have solved it. But I have a new question. I run the code but can't get the .mp4 file. It reminds me "'ffmpeg' is not an internal or external command, nor is it a runnable program or batch file." But I convert "RECORD_VIDEO" to true. could you please answer me this question? Thank you soooo much.

**Comment by Elias-Gu** [comment]
Sounds like you might need to install ffmpeg on your machine: https://www.ffmpeg.org/

**Comment by YunkangTao** [comment]
> Sounds like you might need to install ffmpeg on your machine: https://www.ffmpeg.org/

thank you sooo much!!!

**Comment by DUT-XYZ** [comment]
I downloaded all the code. For Drysand and Water, i can run it successfully. However, for snow and elastic model, there might be some errors in the code. I dont know if there is a grammer error here because VS showed red dashes here and if I "//" annotate this part, it can run but only for drysand and water because these two materials will not run this function.

**Comment by DUT-XYZ** [comment]
![Uploading 微信图片_20231130141807.png…]()

**Comment by DUT-XYZ** [comment]
![微信图片_20231130141819](https://github.com/Elias-Gu/MPM2D/assets/152355231/2f6ed1e4-13b2-4f79-bc85-06ff315b0b26)

**Comment by DUT-XYZ** [comment]
![微信图片_20231130141807](https://github.com/Elias-Gu/MPM2D/assets/152355231/2318acae-5d28-4768-8565-508e82c24940)

**Comment by Elias-Gu** [comment]
`std::clamp` is a C++17 function, could it be the issue?

**Comment by DUT-XYZ** [comment]
Thank you. This part now shows no errors. but the elastic part still cannot run. Some errors are shown on the picture
![微信图片_20231201085923](https://github.com/Elias-Gu/MPM2D/assets/152355231/03e0711b-b69f-4a31-87da-3906916a2147)

**Comment by DUT-XYZ** [comment]
![微信图片_20231201085845](https://github.com/Elias-Gu/MPM2D/assets/152355231/93a485b0-37f6-4dc2-91b1-2db1ca512ede)

**Comment by Elias-Gu** [comment]
Looks like the sim is going unstable; it's not too surprising since it's an explicit integration. I think either reducing `DT` (take smaller timesteps, maybe to something like `1e-5`) or `E_elastic` (make the material less stiff) in `constants.h` may solve the issue

**Comment by DUT-XYZ** [comment]
> Looks like the sim is going unstable; it's not too surprising since it's an explicit integration. I think either reducing `DT` (take smaller timesteps, maybe to something like `1e-5`) or `E_elastic` (make the material less stiff) in `constants.h` may solve the issue

Thank you for your help. Codes can run successfully.  However, i cannot log in some webpages on the readme list. Some websites seems like the UCLA intranet sites.

**Comment by Elias-Gu** [comment]
Thanks for letting me know, I updated the links.

**Comment by DUT-XYZ** [comment]
> Thanks for letting me know, I updated the links.

thanks . pdf files can be downloaded.
